set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[0]}]
set_property PACKAGE_PIN Y16 [get_ports {gpio_rtl_tri_o[2]}]
set_property PACKAGE_PIN Y17 [get_ports {gpio_rtl_tri_o[1]}]
set_property PACKAGE_PIN R14 [get_ports {gpio_rtl_tri_o[0]}]
